Protect against possible character injection (rhbz#1028037).
The first argument of a syslog.err call needs to be "%s" formation
string, otherwise specialy crafted exception message may result
in exception. E.g.

> syslog.err "% "
ArgumentError: invalid format character - %
from (pry):48:in `err'
> syslog.err "%s", "% "
=> <#Syslog: opened=true, ident="abrt", options=3, facility=8, mask=255>